# Numpy
1. Numpy uses much less memory to store data .
2. Numpy make it extreemely easy to perform mathmetical operation on it .
3. Used for creation of n dimensional array .
4. Finding element in numpy is easy .

In [1]:
import numpy as np 


In [2]:
#list --multiple datatype 
l1 = [20,30,40]
l2 = [50,60,70]
l3 = [20,30,40,[20,30,40]]
print(l1+l2)
print(l3)

[20, 30, 40, 50, 60, 70]
[20, 30, 40, [20, 30, 40]]


In [3]:
#array --single datatype 
a = np.array([20,30,40])
b = np.array([60,70,80])
print(a)
print(b)
print(a+b)
print(a*b)

[20 30 40]
[60 70 80]
[ 80 100 120]
[1200 2100 3200]


## Difference in List and Arrays

1. A List cannot directly handle Mathematical operation while Array can .
2. An array consumes less memory than list .
3. Using array is faster than list .
4. A list can store multiple datatype while you cannot do it with arrays .
5. A list is easier to modify since a list store each element individually it is easier to add and delete an element than an array does
6. In list one can have nested data with different size , while you cannot do the same with array 

## Numpy - Creating Arrays , Slicing and Attributes

In [4]:
# Creation of arrays 
arr = np.array([10,20,30,40])
print(arr)
print(type(arr))

arr2 = np.array([[10,20,30,40],[50,60,70,80]])
print(arr2)
print(type(arr2))

[10 20 30 40]
<class 'numpy.ndarray'>
[[10 20 30 40]
 [50 60 70 80]]
<class 'numpy.ndarray'>


In [5]:
#slicing 
arr = np.array([10,20,30,40])
print(arr[3:])
print(arr[2:])
print(arr[:3])

arr2 = np.array([[10,20,30,40],[50,60,70,80]])
print(arr2[0:2,0:3])
print(arr2[0,1:3]) #[20 30]
print(arr2[1,1:3]) #[60 70]

[40]
[30 40]
[10 20 30]
[[10 20 30]
 [50 60 70]]
[20 30]
[60 70]


In [6]:
#attributes of array
arr = np.array([[10,20,30,40],[50,60,70,80],[20,40,60,80]])
print(np.shape(arr)) #(3,4)
print(np.size(arr)) #12 ---gives elements 
print(np.ndim(arr)) #2
print(arr.dtype)


(3, 4)
12
2
int64


## Inspecting an array 

In [7]:
a = [30,40,20,40,30]
b = [[20,10],[5,30]]
arr = np.array(a)
arr2 = np.array(b)
print(arr.shape) #(5,)
print(arr2.shape) #(2,2)
print(len(arr)) #5
print(len(arr2)) #2
print(np.size(arr)) #5
print(type(arr))
print(arr.dtype)
print(arr.astype(float))
print(arr.dtype)


(5,)
(2, 2)
5
2
5
<class 'numpy.ndarray'>
int64
[30. 40. 20. 40. 30.]
int64


## Mathematical Operations and Functions on Arrays

In [8]:
arr1 = np.array([30,40,60,20,10])
arr2 = np.array([30,20,10,20,20])
print(arr1+arr2)
print(np.add(arr1,arr2))
arr3 = np.array([[30,40],[60,20]])
arr4 = np.array([[30,20],[10,20]])
print(arr3+arr4)


[60 60 70 40 30]
[60 60 70 40 30]
[[60 60]
 [70 40]]


In [9]:
arr1 = np.array([30,40,60,20,10])
arr2 = np.array([30,20,10,20,20])
print(np.subtract(arr1,arr2))
print(arr1-arr2)

# Same with multiply and divide 

[  0  20  50   0 -10]
[  0  20  50   0 -10]


In [10]:
arr1 = np.array([3,4,6,2,10])
arr2 = np.array([3])
np.power(arr1,arr2)

array([  27,   64,  216,    8, 1000])

In [11]:
arr1 = np.array(([  27,   64,  216,    8, 1000]))
np.sqrt(arr1)


array([ 5.19615242,  8.        , 14.69693846,  2.82842712, 31.6227766 ])

## Combining and splitting arrays 

In [12]:
a = [30,40,50]
b = [5,5,3]
print(a+b)

[30, 40, 50, 5, 5, 3]


In [13]:
#concatenate
import numpy as np
arr1 = np.array([30,40,50])
arr2 = np.array([5,5,3])
np.concatenate([arr1,arr2])

array([30, 40, 50,  5,  5,  3])

In [14]:
arr1 = np.array([[30,40],[50,40]])
arr2 = np.array([[5,5],[7,8]])
np.concatenate([arr1,arr2],axis=1)

array([[30, 40,  5,  5],
       [50, 40,  7,  8]])

In [15]:
#horizontal stack ---->horizontal concatenation
print(np.hstack([arr1,arr2]))

[[30 40  5  5]
 [50 40  7  8]]


In [16]:
#vertical stack ------>vertical concatenation
print(np.vstack([arr1,arr2]))

[[30 40]
 [50 40]
 [ 5  5]
 [ 7  8]]


In [17]:
#split arrays 
a = np.array([20,40,30,40,10,20])
print(np.array_split(a,3))
print(a)

[array([20, 40]), array([30, 40]), array([10, 20])]
[20 40 30 40 10 20]


## Adding and removing element in Arrays

In [18]:
#append
a = np.array([20,40,60,80])
print(np.append(a,90))

b = np.array([[20,40],[60,80]])
np.append(b,90)
np.append(b,[3,4])

[20 40 60 80 90]


array([20, 40, 60, 80,  3,  4])

In [19]:
#insert
a = np.array([20,40,60,80])
np.insert(a,1,5) #array , index,value. 
# array([20,  5, 40, 60, 80])

b = np.array([[20,40],[60,80]])
np.insert(b,1,[50,60],axis=1)
# array([[20, 50, 40],
#    [60, 60, 80]])
np.insert(b,1,[50,60],axis=0)
# array([[20, 40],
#    [50, 60],
#    [60, 80]])
np.insert(b,[1,2],[50],axis=0)
# array([[20, 40],
    # [50, 50],
    # [60, 80],
    # [50, 50]])
    


array([[20, 40],
       [50, 50],
       [60, 80],
       [50, 50]])

In [20]:
#delete 
a=  np.array([20,40,60,80])
np.delete(a,1)
# array([20, 60, 80])


array([20, 60, 80])

## Numpy - Sort Filter and Search

In [21]:
ar = np.array([7,6,9,2,8])
np.sort(ar)
ar2 = np.array([[7,6,9],[4,2,5]])
np.sort(ar2)

array([[6, 7, 9],
       [2, 4, 5]])

In [22]:
#search
ar = np.array([7,6,9,2,8])
s = np.where(ar==6)
print(s)
evenElementIndex = np.where(ar%2==0)
print(evenElementIndex)

(array([1]),)
(array([1, 3, 4]),)


In [23]:
#search sorted
ar = np.array([1,2,3,4,5])
ss = np.searchsorted(ar,4)
ss

np.int64(3)

In [24]:
#filter
ar = np.array([20,30,40,50])
fa = [True,False,True,False]

new = ar[fa]
new

array([20, 40])

In [25]:
ar = np.array([20,33,43,50])
fa = ar>35
new = ar[fa]
new
evenfa = ar%2==0
neweven = ar[evenfa]
neweven

array([20, 50])

## Aggregating function in Numpy

In [26]:
a = np.array([20,40,50,70])
print(np.sum(a))
print(np.max(a))
print(np.min(a))
print(np.size(a))
print(np.mean(a))
print(np.cumsum(a)) #cummilative sum 
print(np.cumprod(a))

180
70
20
4
45.0
[ 20  60 110 180]
[     20     800   40000 2800000]


In [34]:
a = [100,150,199,200,250,130]
b = [10,50,30,40,30,10]

price = np.array(a)
quantity = np.array(b)
print(price,"\n",quantity)

c=np.cumprod([price,quantity],axis = 0)
print(c[1].sum())

[100 150 199 200 250 130] 
 [10 50 30 40 30 10]
31270


## Statistical Functions of Numpy

In [42]:
import numpy as np
import statistics as stats
baked_food = [200,300,150,130,200,280,170,188]

a = np.array(baked_food)
print(np.mean(baked_food)) #sum of all values/number of values
print(np.median(baked_food)) #central value after sorting
print(stats.mode(baked_food))
print(np.std(baked_food))
print(np.var(baked_food))


202.25
194.0
200
55.68157235567257
3100.4375


In [ ]:
#-1 inversely relationship 
# 1 proportional relatsionship 
# 0 no relationship

tabacoo_consumption = [30,50,10,30,50,40]
deaths = [100,120,70,100,120,112]

print(np.corrcoef([tabacoo_consumption,deaths]))

[[1.         0.99015454]
 [0.99015454 1.        ]]


In [44]:
price = [300,100,350,150,200]
sales = [10,20,7,17,3]

print(np.corrcoef([price,sales]))

[[ 1.         -0.66621445]
 [-0.66621445  1.        ]]
